source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
autoload -Uz compinit && compinit
source ~/.config/zsh/fzf-tab/fzf-tab.plugin.zsh
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[command]='fg=cyan,bold'
FAST_HIGHLIGHT_STYLES[alias]='fg=cyan,bold'
FAST_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
FAST_HIGHLIGHT_STYLES[function]='fg=yellow,bold'
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

if test -n "$KITTY_INSTALLATION_DIR"; then
	export KITTY_SHELL_INTEGRATION="enabled"
	autoload -Uz -- "$KITTY_INSTALLATION_DIR"/shell-integration/zsh/kitty-integration
	kitty-integration
	unfunction kitty-integration
fi

if test -z "$WIFITUI_THEME"; then
	source ~/.xprofile
fi

source ~/.config/zsh/funcs.zsh
source ~/.config/zsh/opt.zsh

export STARSHIP_CONFIG=/home/zaater/.config/starship/starship.toml
# autoload -Uz bracketed-paste-magic
# zle -N bracketed-paste bracketed-paste-magic
source ~/.alias.sh
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"
# eval "$(fzf --zsh)"
