alias zconf='nvim ~/.zshrc'
alias van='nvim +Man!'
alias iconf='nvim ~/.config/i3/config'
alias iexit='i3-msg exit'
alias ls='eza --icons=automatic'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias l='eza --icons=automatic'
alias ll='eza -l --icons=automatic'
alias la='eza -laa --icons=automatic'
alias cat='bat --plain'
alias batt='bat -l conf'
alias copy='xclip -selection clipboard'
alias ts='tmux-sessionizer'
alias td='tmux detach'
alias tl='tmux ls'
alias tk='tmux kill-session'
alias tka='tmux kill-server'
alias shell='exec $SHELL'
alias open='xdg-open'
alias img='nsxiv'
