# ~/.config/gtk-4.0/settings.ini
[Settings]
gtk-cursor-theme-name=LyraQ-cursors
gtk-theme-name=Dracula
gtk-icon-theme-name=dracula-icons-main
gtk-application-prefer-dark-theme=true
gtk-font-name=Inter 10
