add_newline = false
format = '$directory$git_branch$git_status$character'
right_format = '$git_metrics$status$python$username$hostname'

[character]
success_symbol = "[❯](bold white)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[N](bold yellow)"
vimcmd_visual_symbol = "[V](bold yellow)"
vimcmd_replace_symbol = "[R](bold yellow)"
vimcmd_replace_one_symbol = "[R](bold yellow)"

[status]
disabled = false
format = '[$status]($style) '

[directory]
style = 'bold purple'
read_only = ''

[git_branch]
format = '[$branch]($style) '
symbol = ''
style = 'bold grey'

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = ''
deleted = 'x'

[username]
format = '[$user](yellow)'

[hostname]
format = '[@$hostname](green)'

[python]
format = '[$symbol$version](bold yellow) '
detect_extensions = []


[package]
disabled = true
